# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AttachmentGet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hash': 'str',
        'file': 'str',
        'mime': 'str',
        'size': 'int',
        'extension': 'str',
        'full_path': 'str'
    }

    attribute_map = {
        'hash': 'hash',
        'file': 'file',
        'mime': 'mime',
        'size': 'size',
        'extension': 'extension',
        'full_path': 'full_path'
    }

    def __init__(self, hash=None, file=None, mime=None, size=None, extension=None, full_path=None):  # noqa: E501
        """AttachmentGet - a model defined in Swagger"""  # noqa: E501
        self._hash = None
        self._file = None
        self._mime = None
        self._size = None
        self._extension = None
        self._full_path = None
        self.discriminator = None
        if hash is not None:
            self.hash = hash
        if file is not None:
            self.file = file
        if mime is not None:
            self.mime = mime
        if size is not None:
            self.size = size
        if extension is not None:
            self.extension = extension
        if full_path is not None:
            self.full_path = full_path

    @property
    def hash(self):
        """Gets the hash of this AttachmentGet.  # noqa: E501


        :return: The hash of this AttachmentGet.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this AttachmentGet.


        :param hash: The hash of this AttachmentGet.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def file(self):
        """Gets the file of this AttachmentGet.  # noqa: E501


        :return: The file of this AttachmentGet.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this AttachmentGet.


        :param file: The file of this AttachmentGet.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def mime(self):
        """Gets the mime of this AttachmentGet.  # noqa: E501


        :return: The mime of this AttachmentGet.  # noqa: E501
        :rtype: str
        """
        return self._mime

    @mime.setter
    def mime(self, mime):
        """Sets the mime of this AttachmentGet.


        :param mime: The mime of this AttachmentGet.  # noqa: E501
        :type: str
        """

        self._mime = mime

    @property
    def size(self):
        """Gets the size of this AttachmentGet.  # noqa: E501


        :return: The size of this AttachmentGet.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this AttachmentGet.


        :param size: The size of this AttachmentGet.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def extension(self):
        """Gets the extension of this AttachmentGet.  # noqa: E501


        :return: The extension of this AttachmentGet.  # noqa: E501
        :rtype: str
        """
        return self._extension

    @extension.setter
    def extension(self, extension):
        """Sets the extension of this AttachmentGet.


        :param extension: The extension of this AttachmentGet.  # noqa: E501
        :type: str
        """

        self._extension = extension

    @property
    def full_path(self):
        """Gets the full_path of this AttachmentGet.  # noqa: E501


        :return: The full_path of this AttachmentGet.  # noqa: E501
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """Sets the full_path of this AttachmentGet.


        :param full_path: The full_path of this AttachmentGet.  # noqa: E501
        :type: str
        """

        self._full_path = full_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AttachmentGet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttachmentGet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
