# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from qaseio.models.plan import Plan  # noqa: F401,E501

class PlanDetailed(Plan):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'average_time': 'float',
        'cases': 'list[PlanDetailedCases]'
    }
    if hasattr(Plan, "swagger_types"):
        swagger_types.update(Plan.swagger_types)

    attribute_map = {
        'average_time': 'average_time',
        'cases': 'cases'
    }
    if hasattr(Plan, "attribute_map"):
        attribute_map.update(Plan.attribute_map)

    def __init__(self, average_time=None, cases=None, *args, **kwargs):  # noqa: E501
        """PlanDetailed - a model defined in Swagger"""  # noqa: E501
        self._average_time = None
        self._cases = None
        self.discriminator = None
        if average_time is not None:
            self.average_time = average_time
        if cases is not None:
            self.cases = cases
        Plan.__init__(self, *args, **kwargs)

    @property
    def average_time(self):
        """Gets the average_time of this PlanDetailed.  # noqa: E501


        :return: The average_time of this PlanDetailed.  # noqa: E501
        :rtype: float
        """
        return self._average_time

    @average_time.setter
    def average_time(self, average_time):
        """Sets the average_time of this PlanDetailed.


        :param average_time: The average_time of this PlanDetailed.  # noqa: E501
        :type: float
        """

        self._average_time = average_time

    @property
    def cases(self):
        """Gets the cases of this PlanDetailed.  # noqa: E501


        :return: The cases of this PlanDetailed.  # noqa: E501
        :rtype: list[PlanDetailedCases]
        """
        return self._cases

    @cases.setter
    def cases(self, cases):
        """Sets the cases of this PlanDetailed.


        :param cases: The cases of this PlanDetailed.  # noqa: E501
        :type: list[PlanDetailedCases]
        """

        self._cases = cases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanDetailed, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanDetailed):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
