# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanCreate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'str',
        'description': 'str',
        'cases': 'list[int]'
    }

    attribute_map = {
        'title': 'title',
        'description': 'description',
        'cases': 'cases'
    }

    def __init__(self, title=None, description=None, cases=None):  # noqa: E501
        """PlanCreate - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._cases = None
        self.discriminator = None
        self.title = title
        if description is not None:
            self.description = description
        self.cases = cases

    @property
    def title(self):
        """Gets the title of this PlanCreate.  # noqa: E501


        :return: The title of this PlanCreate.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this PlanCreate.


        :param title: The title of this PlanCreate.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this PlanCreate.  # noqa: E501


        :return: The description of this PlanCreate.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PlanCreate.


        :param description: The description of this PlanCreate.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def cases(self):
        """Gets the cases of this PlanCreate.  # noqa: E501


        :return: The cases of this PlanCreate.  # noqa: E501
        :rtype: list[int]
        """
        return self._cases

    @cases.setter
    def cases(self, cases):
        """Sets the cases of this PlanCreate.


        :param cases: The cases of this PlanCreate.  # noqa: E501
        :type: list[int]
        """
        if cases is None:
            raise ValueError("Invalid value for `cases`, must not be `None`")  # noqa: E501

        self._cases = cases

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanCreate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanCreate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
