# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanDetailedCases(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'case_id': 'int',
        'assignee_id': 'int'
    }

    attribute_map = {
        'case_id': 'case_id',
        'assignee_id': 'assignee_id'
    }

    def __init__(self, case_id=None, assignee_id=None):  # noqa: E501
        """PlanDetailedCases - a model defined in Swagger"""  # noqa: E501
        self._case_id = None
        self._assignee_id = None
        self.discriminator = None
        if case_id is not None:
            self.case_id = case_id
        if assignee_id is not None:
            self.assignee_id = assignee_id

    @property
    def case_id(self):
        """Gets the case_id of this PlanDetailedCases.  # noqa: E501


        :return: The case_id of this PlanDetailedCases.  # noqa: E501
        :rtype: int
        """
        return self._case_id

    @case_id.setter
    def case_id(self, case_id):
        """Sets the case_id of this PlanDetailedCases.


        :param case_id: The case_id of this PlanDetailedCases.  # noqa: E501
        :type: int
        """

        self._case_id = case_id

    @property
    def assignee_id(self):
        """Gets the assignee_id of this PlanDetailedCases.  # noqa: E501


        :return: The assignee_id of this PlanDetailedCases.  # noqa: E501
        :rtype: int
        """
        return self._assignee_id

    @assignee_id.setter
    def assignee_id(self, assignee_id):
        """Sets the assignee_id of this PlanDetailedCases.


        :param assignee_id: The assignee_id of this PlanDetailedCases.  # noqa: E501
        :type: int
        """

        self._assignee_id = assignee_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanDetailedCases, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanDetailedCases):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
