# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectCountsRuns(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'active': 'int'
    }

    attribute_map = {
        'total': 'total',
        'active': 'active'
    }

    def __init__(self, total=None, active=None):  # noqa: E501
        """ProjectCountsRuns - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._active = None
        self.discriminator = None
        if total is not None:
            self.total = total
        if active is not None:
            self.active = active

    @property
    def total(self):
        """Gets the total of this ProjectCountsRuns.  # noqa: E501


        :return: The total of this ProjectCountsRuns.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ProjectCountsRuns.


        :param total: The total of this ProjectCountsRuns.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def active(self):
        """Gets the active of this ProjectCountsRuns.  # noqa: E501


        :return: The active of this ProjectCountsRuns.  # noqa: E501
        :rtype: int
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ProjectCountsRuns.


        :param active: The active of this ProjectCountsRuns.  # noqa: E501
        :type: int
        """

        self._active = active

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectCountsRuns, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectCountsRuns):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
