"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.environment_list_response_all_of import EnvironmentListResponseAllOf
from qaseio.model.environment_list_response_all_of_result import EnvironmentListResponseAllOfResult
from qaseio.model.response import Response
globals()['EnvironmentListResponseAllOf'] = EnvironmentListResponseAllOf
globals()['EnvironmentListResponseAllOfResult'] = EnvironmentListResponseAllOfResult
globals()['Response'] = Response
from qaseio.model.environment_list_response import EnvironmentListResponse


class TestEnvironmentListResponse(unittest.TestCase):
    """EnvironmentListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentListResponse(self):
        """Test EnvironmentListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvironmentListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
