# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qaseio
from qaseio.models.run_stats import RunStats  # noqa: E501
from qaseio.rest import ApiException


class TestRunStats(unittest.TestCase):
    """RunStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunStats(self):
        """Test RunStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qaseio.models.run_stats.RunStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
