# coding: utf-8

"""
    Qase.io TestOps API

    Qase TestOps API Specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qaseio.models.shared_step_update import SharedStepUpdate

class TestSharedStepUpdate(unittest.TestCase):
    """SharedStepUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SharedStepUpdate:
        """Test SharedStepUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SharedStepUpdate`
        """
        model = SharedStepUpdate()
        if include_optional:
            return SharedStepUpdate(
                title = '',
                action = '',
                expected_result = '',
                data = '',
                steps = [
                    qaseio.models.shared_step_content_create.SharedStepContentCreate(
                        hash = '', 
                        action = '', 
                        expected_result = '', 
                        data = '', 
                        attachments = [
                            ''
                            ], )
                    ]
            )
        else:
            return SharedStepUpdate(
                title = '',
        )
        """

    def testSharedStepUpdate(self):
        """Test SharedStepUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
