# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qaseio
from qaseio.models.test_case_create_steps import TestCaseCreateSteps  # noqa: E501
from qaseio.rest import ApiException


class TestTestCaseCreateSteps(unittest.TestCase):
    """TestCaseCreateSteps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCaseCreateSteps(self):
        """Test TestCaseCreateSteps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qaseio.models.test_case_create_steps.TestCaseCreateSteps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
