"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.filters4 import Filters4


class TestFilters4(unittest.TestCase):
    """Filters4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilters4(self):
        """Test Filters4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Filters4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
