"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.test_case import TestCase
globals()['TestCase'] = TestCase
from qaseio.model.test_case_response_all_of import TestCaseResponseAllOf


class TestTestCaseResponseAllOf(unittest.TestCase):
    """TestCaseResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCaseResponseAllOf(self):
        """Test TestCaseResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestCaseResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
