"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.response import Response
from qaseio.model.run import Run
from qaseio.model.run_response_all_of import RunResponseAllOf
globals()['Response'] = Response
globals()['Run'] = Run
globals()['RunResponseAllOf'] = RunResponseAllOf
from qaseio.model.run_response import RunResponse


class TestRunResponse(unittest.TestCase):
    """RunResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunResponse(self):
        """Test RunResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
