"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.project_counts_defects import ProjectCountsDefects
from qaseio.model.project_counts_runs import ProjectCountsRuns
globals()['ProjectCountsDefects'] = ProjectCountsDefects
globals()['ProjectCountsRuns'] = ProjectCountsRuns
from qaseio.model.project_counts import ProjectCounts


class TestProjectCounts(unittest.TestCase):
    """ProjectCounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectCounts(self):
        """Test ProjectCounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectCounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
