"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.environment import Environment
from qaseio.model.environment_response_all_of import EnvironmentResponseAllOf
from qaseio.model.response import Response
globals()['Environment'] = Environment
globals()['EnvironmentResponseAllOf'] = EnvironmentResponseAllOf
globals()['Response'] = Response
from qaseio.model.environment_response import EnvironmentResponse


class TestEnvironmentResponse(unittest.TestCase):
    """EnvironmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentResponse(self):
        """Test EnvironmentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvironmentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
