"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.project import Project
from qaseio.model.project_response_all_of import ProjectResponseAllOf
from qaseio.model.response import Response
globals()['Project'] = Project
globals()['ProjectResponseAllOf'] = ProjectResponseAllOf
globals()['Response'] = Response
from qaseio.model.project_response import ProjectResponse


class TestProjectResponse(unittest.TestCase):
    """ProjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectResponse(self):
        """Test ProjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
