"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.milestone import Milestone
globals()['Milestone'] = Milestone
from qaseio.model.milestone_response_all_of import MilestoneResponseAllOf


class TestMilestoneResponseAllOf(unittest.TestCase):
    """MilestoneResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMilestoneResponseAllOf(self):
        """Test MilestoneResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MilestoneResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
