"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.defect_list_response_all_of_result import DefectListResponseAllOfResult
globals()['DefectListResponseAllOfResult'] = DefectListResponseAllOfResult
from qaseio.model.defect_list_response_all_of import DefectListResponseAllOf


class TestDefectListResponseAllOf(unittest.TestCase):
    """DefectListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefectListResponseAllOf(self):
        """Test DefectListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DefectListResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
