"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.bulk200_response_all_of_result import Bulk200ResponseAllOfResult
globals()['Bulk200ResponseAllOfResult'] = Bulk200ResponseAllOfResult
from qaseio.model.bulk200_response_all_of import Bulk200ResponseAllOf


class TestBulk200ResponseAllOf(unittest.TestCase):
    """Bulk200ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulk200ResponseAllOf(self):
        """Test Bulk200ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Bulk200ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
