# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qaseio
from qaseio.models.filters2 import Filters2  # noqa: E501
from qaseio.rest import ApiException


class TestFilters2(unittest.TestCase):
    """Filters2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilters2(self):
        """Test Filters2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qaseio.models.filters2.Filters2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
