"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.defect_status import DefectStatus


class TestDefectStatus(unittest.TestCase):
    """DefectStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefectStatus(self):
        """Test DefectStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DefectStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
