"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.filters6 import Filters6


class TestFilters6(unittest.TestCase):
    """Filters6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilters6(self):
        """Test Filters6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Filters6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
