"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.run_list_response_all_of_result import RunListResponseAllOfResult
globals()['RunListResponseAllOfResult'] = RunListResponseAllOfResult
from qaseio.model.run_list_response_all_of import RunListResponseAllOf


class TestRunListResponseAllOf(unittest.TestCase):
    """RunListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunListResponseAllOf(self):
        """Test RunListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RunListResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
