# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@qase.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import qaseio
from qaseio.models.plan_create import PlanCreate  # noqa: E501
from qaseio.rest import ApiException


class TestPlanCreate(unittest.TestCase):
    """PlanCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlanCreate(self):
        """Test PlanCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = qaseio.models.plan_create.PlanCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
