"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.author_list_response_all_of_result import AuthorListResponseAllOfResult
globals()['AuthorListResponseAllOfResult'] = AuthorListResponseAllOfResult
from qaseio.model.author_list_response_all_of import AuthorListResponseAllOf


class TestAuthorListResponseAllOf(unittest.TestCase):
    """AuthorListResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthorListResponseAllOf(self):
        """Test AuthorListResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthorListResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
