"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.shared_step_create_steps_inner import SharedStepCreateStepsInner
globals()['SharedStepCreateStepsInner'] = SharedStepCreateStepsInner
from qaseio.model.shared_step_create import SharedStepCreate


class TestSharedStepCreate(unittest.TestCase):
    """SharedStepCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSharedStepCreate(self):
        """Test SharedStepCreate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SharedStepCreate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
