"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.response import Response
from qaseio.model.shared_step_list_response_all_of import SharedStepListResponseAllOf
from qaseio.model.shared_step_list_response_all_of_result import SharedStepListResponseAllOfResult
globals()['Response'] = Response
globals()['SharedStepListResponseAllOf'] = SharedStepListResponseAllOf
globals()['SharedStepListResponseAllOfResult'] = SharedStepListResponseAllOfResult
from qaseio.model.shared_step_list_response import SharedStepListResponse


class TestSharedStepListResponse(unittest.TestCase):
    """SharedStepListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSharedStepListResponse(self):
        """Test SharedStepListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SharedStepListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
