"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.attachment_hash_list import AttachmentHashList
globals()['AttachmentHashList'] = AttachmentHashList
from qaseio.model.test_case_create_steps import TestCaseCreateSteps


class TestTestCaseCreateSteps(unittest.TestCase):
    """TestCaseCreateSteps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCaseCreateSteps(self):
        """Test TestCaseCreateSteps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestCaseCreateSteps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
