"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qaseio
from qaseio.model.suite_update import SuiteUpdate


class TestSuiteUpdate(unittest.TestCase):
    """SuiteUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuiteUpdate(self):
        """Test SuiteUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuiteUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
