from enum import Enum

class Envs(Enum):
    DEBUG = "QASE_DEBUG"
    MODE = "QASE_MODE"
    ENVIRONMENT = "QASE_ENVIRONMENT"

    TESTOPS_MODE = "QASE_TESTOPS_MODE"
    TESTOPS_HOST = "QASE_TESTOPS_HOST"
    TESTOPS_API_TOKEN = "QASE_TESTOPS_API_TOKEN"
    TESTOPS_PROJECT = "QASE_TESTOPS_PROJECT"
    TESTOPS_RUN_ID = "QASE_TESTOPS_RUN_ID"
    TESTOPS_PLAN_ID = "QASE_TESTOPS_PLAN_ID"
    TESTOPS_RUN_TITLE = "QASE_TESTOPS_RUN_TITLE"
    TESTOPS_COMPLETE_RUN = "QASE_TESTOPS_COMPLETE_RUN"

STATUSES = {
    "PASS": "passed",
    "FAIL": "failed",
    "SKIP": "skipped",
    "NOT RUN": "skipped",
    "NOT_SET": "skipped"
}