# coding: utf-8

"""
    Qase.io TestOps API v1

    Qase TestOps API v1 Specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from qase.api_client_v1.models.review_step_data import ReviewStepData
from qase.api_client_v1.models.test_case_parameter_create import TestCaseParameterCreate
from typing import Optional, Set
from typing_extensions import Self

class ReviewCaseData(BaseModel):
    """
    The test case fields proposed by the review.
    """ # noqa: E501
    title: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    description: Optional[StrictStr] = None
    preconditions: Optional[StrictStr] = None
    postconditions: Optional[StrictStr] = None
    severity: Optional[StrictInt] = None
    priority: Optional[StrictInt] = None
    behavior: Optional[StrictInt] = None
    type: Optional[StrictInt] = None
    layer: Optional[StrictInt] = None
    is_flaky: Optional[StrictInt] = None
    is_muted: Optional[StrictBool] = Field(default=None, description="Mute state of the proposed test case.")
    suite_id: Optional[StrictInt] = None
    milestone_id: Optional[StrictInt] = None
    is_manual: Optional[StrictBool] = Field(default=None, description="`true` if the case is manual, `false` if it is automated.")
    is_to_be_automated: Optional[StrictBool] = Field(default=None, description="`true` if a manual case is planned to be automated.")
    status: Optional[StrictInt] = None
    steps_type: Optional[StrictStr] = Field(default=None, description="Format of the steps field. Omit to keep the current one, `classic` for a new-case draft; changing it requires sending `steps` in the same request.")
    attachments: Optional[List[StrictStr]] = Field(default=None, description="A list of Attachment hashes.")
    steps: Optional[List[ReviewStepData]] = Field(default=None, description="For gherkin steps send the scenario in `value`.")
    tags: Optional[List[StrictStr]] = None
    parameters: Optional[List[TestCaseParameterCreate]] = None
    custom_field: Optional[Dict[str, StrictStr]] = Field(default=None, description="Map of custom field ID to value. A `create` review must carry every required custom field. An `edit` review is validated against the current test case, so send only the fields the proposal changes.")
    __properties: ClassVar[List[str]] = ["title", "description", "preconditions", "postconditions", "severity", "priority", "behavior", "type", "layer", "is_flaky", "is_muted", "suite_id", "milestone_id", "is_manual", "is_to_be_automated", "status", "steps_type", "attachments", "steps", "tags", "parameters", "custom_field"]

    @field_validator('steps_type')
    def steps_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['classic', 'gherkin']):
            raise ValueError("must be one of enum values ('classic', 'gherkin')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewCaseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                if _item_steps:
                    _items.append(_item_steps.to_dict())
            _dict['steps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in parameters (list)
        _items = []
        if self.parameters:
            for _item_parameters in self.parameters:
                if _item_parameters:
                    _items.append(_item_parameters.to_dict())
            _dict['parameters'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if preconditions (nullable) is None
        # and model_fields_set contains the field
        if self.preconditions is None and "preconditions" in self.model_fields_set:
            _dict['preconditions'] = None

        # set to None if postconditions (nullable) is None
        # and model_fields_set contains the field
        if self.postconditions is None and "postconditions" in self.model_fields_set:
            _dict['postconditions'] = None

        # set to None if severity (nullable) is None
        # and model_fields_set contains the field
        if self.severity is None and "severity" in self.model_fields_set:
            _dict['severity'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if behavior (nullable) is None
        # and model_fields_set contains the field
        if self.behavior is None and "behavior" in self.model_fields_set:
            _dict['behavior'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if layer (nullable) is None
        # and model_fields_set contains the field
        if self.layer is None and "layer" in self.model_fields_set:
            _dict['layer'] = None

        # set to None if is_flaky (nullable) is None
        # and model_fields_set contains the field
        if self.is_flaky is None and "is_flaky" in self.model_fields_set:
            _dict['is_flaky'] = None

        # set to None if suite_id (nullable) is None
        # and model_fields_set contains the field
        if self.suite_id is None and "suite_id" in self.model_fields_set:
            _dict['suite_id'] = None

        # set to None if milestone_id (nullable) is None
        # and model_fields_set contains the field
        if self.milestone_id is None and "milestone_id" in self.model_fields_set:
            _dict['milestone_id'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if parameters (nullable) is None
        # and model_fields_set contains the field
        if self.parameters is None and "parameters" in self.model_fields_set:
            _dict['parameters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewCaseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "preconditions": obj.get("preconditions"),
            "postconditions": obj.get("postconditions"),
            "severity": obj.get("severity"),
            "priority": obj.get("priority"),
            "behavior": obj.get("behavior"),
            "type": obj.get("type"),
            "layer": obj.get("layer"),
            "is_flaky": obj.get("is_flaky"),
            "is_muted": obj.get("is_muted"),
            "suite_id": obj.get("suite_id"),
            "milestone_id": obj.get("milestone_id"),
            "is_manual": obj.get("is_manual"),
            "is_to_be_automated": obj.get("is_to_be_automated"),
            "status": obj.get("status"),
            "steps_type": obj.get("steps_type"),
            "attachments": obj.get("attachments"),
            "steps": [ReviewStepData.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None,
            "tags": obj.get("tags"),
            "parameters": [TestCaseParameterCreate.from_dict(_item) for _item in obj["parameters"]] if obj.get("parameters") is not None else None,
            "custom_field": obj.get("custom_field")
        })
        return _obj


