# coding: utf-8

"""
    Qase.io TestOps API v1

    Qase TestOps API v1 Specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qase.api_client_v1.models.milestone_create import MilestoneCreate

class TestMilestoneCreate(unittest.TestCase):
    """MilestoneCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MilestoneCreate:
        """Test MilestoneCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MilestoneCreate`
        """
        model = MilestoneCreate()
        if include_optional:
            return MilestoneCreate(
                title = '',
                description = '',
                status = 'completed',
                due_date = 56
            )
        else:
            return MilestoneCreate(
                title = '',
        )
        """

    def testMilestoneCreate(self):
        """Test MilestoneCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
