# coding: utf-8

"""
    Qase.io TestOps API v1

    Qase TestOps API v1 Specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qase.api_client_v1.models.id_response import IdResponse

class TestIdResponse(unittest.TestCase):
    """IdResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdResponse:
        """Test IdResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdResponse`
        """
        model = IdResponse()
        if include_optional:
            return IdResponse(
                status = True,
                result = qase.api_client_v1.models.id_response_all_of_result.IdResponse_allOf_result(
                    id = 56, )
            )
        else:
            return IdResponse(
        )
        """

    def testIdResponse(self):
        """Test IdResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
