# coding: utf-8

"""
    Qase.io TestOps API v1

    Qase TestOps API v1 Specification.

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qase.api_client_v1.models.requirement import Requirement

class TestRequirement(unittest.TestCase):
    """Requirement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Requirement:
        """Test Requirement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Requirement`
        """
        model = Requirement()
        if include_optional:
            return Requirement(
                id = 56,
                requirement_id = 56,
                parent_id = 56,
                member_id = 56,
                title = '',
                description = '',
                status = 'valid',
                type = 'epic',
                created_at = '2021-12-30T19:23:59Z',
                updated_at = '2021-12-30T19:23:59Z'
            )
        else:
            return Requirement(
        )
        """

    def testRequirement(self):
        """Test Requirement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
