# coding: utf-8

"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""

import unittest

import qaseio
from qaseio.model.suite_update import SuiteUpdate
from qaseio import configuration


class TestSuiteUpdate(unittest.TestCase):
    """SuiteUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
