"""
    Qase.io API

    Qase API Specification.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@qase.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from qaseio.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from qaseio.model.attachment_hash_list import AttachmentHashList
    from qaseio.model.test_case_create_steps import TestCaseCreateSteps
    globals()['AttachmentHashList'] = AttachmentHashList
    globals()['TestCaseCreateSteps'] = TestCaseCreateSteps


class TestCaseCreate(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('title',): {
            'max_length': 255,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'title': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'preconditions': (str,),  # noqa: E501
            'postconditions': (str,),  # noqa: E501
            'severity': (int,),  # noqa: E501
            'priority': (int,),  # noqa: E501
            'behavior': (int,),  # noqa: E501
            'type': (int,),  # noqa: E501
            'layer': (int,),  # noqa: E501
            'is_flaky': (int,),  # noqa: E501
            'suite_id': (int,),  # noqa: E501
            'milestone_id': (int,),  # noqa: E501
            'automation': (int,),  # noqa: E501
            'status': (int,),  # noqa: E501
            'attachments': (AttachmentHashList,),  # noqa: E501
            'steps': ([TestCaseCreateSteps],),  # noqa: E501
            'tags': ([str],),  # noqa: E501
            'custom_field': ({str: (str,)},),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'title': 'title',  # noqa: E501
        'description': 'description',  # noqa: E501
        'preconditions': 'preconditions',  # noqa: E501
        'postconditions': 'postconditions',  # noqa: E501
        'severity': 'severity',  # noqa: E501
        'priority': 'priority',  # noqa: E501
        'behavior': 'behavior',  # noqa: E501
        'type': 'type',  # noqa: E501
        'layer': 'layer',  # noqa: E501
        'is_flaky': 'is_flaky',  # noqa: E501
        'suite_id': 'suite_id',  # noqa: E501
        'milestone_id': 'milestone_id',  # noqa: E501
        'automation': 'automation',  # noqa: E501
        'status': 'status',  # noqa: E501
        'attachments': 'attachments',  # noqa: E501
        'steps': 'steps',  # noqa: E501
        'tags': 'tags',  # noqa: E501
        'custom_field': 'custom_field',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, title, *args, **kwargs):  # noqa: E501
        """TestCaseCreate - a model defined in OpenAPI

        Args:
            title (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            description (str): [optional]  # noqa: E501
            preconditions (str): [optional]  # noqa: E501
            postconditions (str): [optional]  # noqa: E501
            severity (int): [optional]  # noqa: E501
            priority (int): [optional]  # noqa: E501
            behavior (int): [optional]  # noqa: E501
            type (int): [optional]  # noqa: E501
            layer (int): [optional]  # noqa: E501
            is_flaky (int): [optional]  # noqa: E501
            suite_id (int): [optional]  # noqa: E501
            milestone_id (int): [optional]  # noqa: E501
            automation (int): [optional]  # noqa: E501
            status (int): [optional]  # noqa: E501
            attachments (AttachmentHashList): [optional]  # noqa: E501
            steps ([TestCaseCreateSteps]): [optional]  # noqa: E501
            tags ([str]): [optional]  # noqa: E501
            custom_field ({str: (str,)}): A map of custom fields values (id => value). [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.title = title
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
